// Types for the static JSON artifacts under web/data/, generated by
// scripts/export_web_results.py from real results/ and data/processed/
// output. The portal never fabricates data -- these types describe exactly
// what that script writes, nothing more.

export type ModelId =
  | "tfidf"
  | "bm25"
  | "bge"
  | "medcpt"
  | "hybrid_rrf"
  | "hybrid_reranked";

export interface ModelMeta {
  id: ModelId;
  name: string;
  family: string;
  huggingface: string | null;
  description: string;
  config: string;
}

export interface ResearchStatusEntry {
  milestone: string;
  description: string;
  status: "complete" | "in_progress" | "pending" | "failed";
}

export interface MainResultRow {
  model: string;
  "P@10": string;
  "Recall@100": string;
  MAP: string;
  "MRR@10": string;
  "nDCG@10": string;
  "Latency (ms/query)": string;
}

export interface SignificanceComparison {
  metric: string;
  model_a: string;
  model_b: string;
  mean_a: number;
  mean_b: number;
  mean_diff: number;
  ci_95_low: number;
  ci_95_high: number;
  p_value: number;
  n_queries: number;
  n_resamples: number;
  method: string;
  effect_direction: string;
  "significant_at_alpha_0.05": boolean;
}

export interface ComparisonData {
  main_results: MainResultRow[];
  statistical_tests: {
    method: string;
    n_resamples: number;
    seed: number;
    alpha: number;
    comparisons: SignificanceComparison[];
  };
}

export interface ModelMetrics {
  model: string;
  config_path?: string;
  parameters?: Record<string, unknown>;
  split: string;
  num_queries_evaluated: number;
  metrics: Record<string, number>;
  timing?: Record<string, number | string | null>;
  index?: Record<string, number | string | null>;
  device?: string;
}

export type MetricsData = Record<string, ModelMetrics>;

export interface EfficiencyRow {
  model: string;
  status: "complete" | "missing";
  device?: string;
  embedding_dim?: number | null;
  index_size_bytes?: number | null;
  latency_ms_per_query?: number | null;
  "nDCG@10"?: number;
  MAP?: number;
  "Recall@100"?: number;
}

export interface ErrorExample {
  category: string;
  query_id: string;
  query: string;
  doc_id: string;
  relevance: number;
  doc_title: string;
  doc_snippet: string;
  ranks: Record<string, number | null>;
}

export interface ErrorAnalysisData {
  description: string;
  rank_thresholds: { good_rank: number; bad_rank: number };
  total_examples_found_per_category: Record<string, number>;
  examples_shown_per_category: number;
  categories: Record<string, ErrorExample[]>;
}

export interface ExperimentManifest {
  experiment_id: string;
  timestamp: string;
  git_commit: string;
  dataset: string;
  dataset_revision: string | null;
  split: string;
  model: string;
  model_revision: string | null;
  parameters: Record<string, unknown>;
  seed: number;
  device: string;
  python_version: string;
  os?: string;
  library_versions: Record<string, string>;
  runtime_seconds: number;
  status: "pending" | "running" | "complete" | "failed";
  error?: string;
  [key: string]: unknown;
}

export interface DatasetData {
  provenance: Record<string, unknown>;
  validation: {
    ok: boolean;
    errors: string[];
    warnings: string[];
    stats: Record<string, unknown>;
  };
  corpus_size: number;
  query_count: number;
  qrel_counts: Record<string, number>;
  splits: Record<string, { role: string }>;
  corpus_detail: Record<string, unknown>;
  query_detail: Record<string, unknown>;
}
